"""
Industrial Multi-Camera Tracking (MTMCT) Core API Service & Live WebSockets Broadcaster.
"""
import asyncio
import base64
import json
from pathlib import Path
import time
from typing import Dict, List, Optional

import cv2
from fastapi import FastAPI, Query, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from src.mtmct_pipeline import MTMCTPipelineEngine

app = FastAPI(
    title="Industrial MTMCT Tracking & Spatial API",
    description="Backend service for cross-camera tracking, instant subject search, and spatial trajectory analytics.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global pipeline engine instance
PIPELINE_ENGINE = MTMCTPipelineEngine(fps=25)


class SubjectLocation(BaseModel):
    subject_id: str
    label: str
    class_name: str
    current_camera_id: str
    world_x: float
    world_y: float
    bounding_box: List[float]
    last_updated: float
    confidence: float


class HistoricalTrajectory(BaseModel):
    subject_id: str
    date: str
    total_distance_meters: float
    dwell_zones: List[str]
    points: List[Dict[str, float]]


@app.get("/", response_class=HTMLResponse)
def serve_dashboard():
    """Serves the primary Digital Twin live operator dashboard."""
    html_path = Path(__file__).parent.parent / "dashboard" / "index.html"
    if html_path.exists():
        return html_path.read_text(encoding="utf-8")
    return "<h1>MTMCT Engine Dashboard Loaded</h1>"


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "mtmct-engine",
        "timestamp": time.time(),
        "active_subjects": len(PIPELINE_ENGINE.graph_matcher.global_tracks)
    }


@app.get("/api/v1/search", response_model=Optional[SubjectLocation])
def search_subject(query: str = Query(..., description="Subject ID or Name (e.g. VSL-402, EMP-101)")):
    """Instant search endpoint to locate any registered person or vessel."""
    query_upper = query.strip().upper()
    for gid, gt in PIPELINE_ENGINE.graph_matcher.global_tracks.items():
        if query_upper in gid.upper() or query_upper in gt.label.upper():
            return SubjectLocation(
                subject_id=gt.global_id,
                label=gt.label,
                class_name=gt.class_name,
                current_camera_id=gt.current_camera,
                world_x=gt.world_coords[0],
                world_y=gt.world_coords[1],
                bounding_box=list(gt.bounding_box),
                last_updated=gt.last_updated,
                confidence=0.94
            )
    return None


@app.get("/api/v1/trajectory", response_model=HistoricalTrajectory)
def get_historical_trajectory(subject_id: str, date: Optional[str] = None):
    """Retrieves recorded spatial trajectory path, total distance traveled, and visited dwell zones."""
    gt = PIPELINE_ENGINE.graph_matcher.global_tracks.get(subject_id)
    if gt and gt.trajectory:
        pts = [
            {"x": p[0], "y": p[1], "timestamp": p[2], "camera_id": p[3]}
            for p in gt.trajectory
        ]
        # Compute total distance
        total_dist = 0.0
        for i in range(1, len(gt.trajectory)):
            p1, p2 = gt.trajectory[i - 1], gt.trajectory[i]
            total_dist += float(((p2[0] - p1[0])**2 + (p2[1] - p1[1])**2)**0.5)

        dwell_zones = list(PIPELINE_ENGINE.spatial_analytics.total_zone_dwell_times.get(subject_id, {}).keys())
        return HistoricalTrajectory(
            subject_id=subject_id,
            date=date or "2026-09-24",
            total_distance_meters=round(total_dist, 2),
            dwell_zones=dwell_zones or ["Zone_A_Entrance"],
            points=pts
        )

    return HistoricalTrajectory(
        subject_id=subject_id,
        date=date or "2026-09-24",
        total_distance_meters=0.0,
        dwell_zones=[],
        points=[]
    )


@app.get("/api/v1/zones")
def get_factory_zones():
    """Returns factory floor zone definitions and hazard classifications."""
    return [
        {
            "zone_id": z.zone_id,
            "name": z.name,
            "polygon": z.polygon,
            "is_hazard": z.is_hazard,
            "max_speed": z.max_authorized_speed_mps
        }
        for z in PIPELINE_ENGINE.spatial_analytics.zones.values()
    ]


@app.get("/api/v1/alerts")
def get_active_alerts():
    """Returns historical safety alerts generated by the spatial analytics engine."""
    return [
        {
            "alert_id": a.alert_id,
            "timestamp": a.timestamp,
            "zone_id": a.zone_id,
            "zone_name": a.zone_name,
            "subject_id": a.subject_id,
            "subject_label": a.subject_label,
            "alert_type": a.alert_type,
            "severity": a.severity,
            "message": a.message
        }
        for a in PIPELINE_ENGINE.spatial_analytics.active_alerts[-20:]
    ]


@app.get("/api/v1/cameras")
def get_cameras():
    """Returns camera positions, look-at targets, and FOV frustums for 2D map rendering."""
    cams = []
    cam_colors = {
        "CAM_01_GATE_NORTH": "#00e5ff",
        "CAM_02_AISLE_WEST": "#00ff88",
        "CAM_03_REACTOR_BAY": "#ffb800",
        "CAM_04_LOADING_DOCK": "#b026ff"
    }
    for cid, cam in PIPELINE_ENGINE.simulator.cameras.items():
        cams.append({
            "id": cid,
            "name": cam.name,
            "pos": [float(cam.pos_3d[0]), float(cam.pos_3d[1]), float(cam.pos_3d[2])],
            "target": [float(cam.target_3d[0]), float(cam.target_3d[1]), float(cam.target_3d[2])],
            "fov_deg": float(cam.fov_deg),
            "color": cam_colors.get(cid, "#00e5ff")
        })
    return cams


@app.websocket("/ws/live-tracking")
async def live_tracking_stream(websocket: WebSocket):
    """WebSockets stream broadcasting real-time synchronized video thumbnails, bounding boxes, and floor coordinates."""
    await websocket.accept()
    cam_colors = {
        "CAM_01_GATE_NORTH": "#00e5ff",
        "CAM_02_AISLE_WEST": "#00ff88",
        "CAM_03_REACTOR_BAY": "#ffb800",
        "CAM_04_LOADING_DOCK": "#b026ff"
    }
    camera_metadata = [
        {
            "id": cid,
            "name": cam.name,
            "pos": [float(cam.pos_3d[0]), float(cam.pos_3d[1]), float(cam.pos_3d[2])],
            "target": [float(cam.target_3d[0]), float(cam.target_3d[1]), float(cam.target_3d[2])],
            "fov_deg": float(cam.fov_deg),
            "color": cam_colors.get(cid, "#00e5ff")
        }
        for cid, cam in PIPELINE_ENGINE.simulator.cameras.items()
    ]
    try:
        while True:
            # Advance pipeline step
            frames, global_tracks, new_alerts = PIPELINE_ENGINE.step()

            # Encode small CCTV thumbnails for UI preview
            encoded_frames = {}
            for cid, f in frames.items():
                thumb = cv2.resize(f, (320, 180))
                _, buffer = cv2.imencode('.jpg', thumb, [cv2.IMWRITE_JPEG_QUALITY, 60])
                encoded_frames[cid] = base64.b64encode(buffer).decode('utf-8')

            # Build structured subject locations
            active_subjects = []
            for gid, gt in global_tracks.items():
                if gt.is_active:
                    active_subjects.append({
                        "subject_id": str(gt.global_id),
                        "label": str(gt.label),
                        "class_name": str(gt.class_name),
                        "current_camera_id": str(gt.current_camera),
                        "world_x": float(gt.world_coords[0]),
                        "world_y": float(gt.world_coords[1]),
                        "bounding_box": [float(v) for v in gt.bounding_box],
                        "last_updated": float(gt.last_updated),
                        "confidence": 0.94
                    })

            alert_dicts = [
                {
                    "alert_id": str(a.alert_id),
                    "timestamp": float(a.timestamp),
                    "zone_id": str(a.zone_id),
                    "zone_name": str(a.zone_name),
                    "subject_id": str(a.subject_id),
                    "alert_type": str(a.alert_type),
                    "severity": str(a.severity),
                    "message": str(a.message)
                }
                for a in new_alerts
            ]

            payload = {
                "timestamp": float(time.time()),
                "active_count": int(len(active_subjects)),
                "subjects": active_subjects,
                "frames": encoded_frames,
                "cameras": camera_metadata,
                "alerts": alert_dicts
            }
            await websocket.send_text(json.dumps(payload))
            await asyncio.sleep(0.04)  # 25 FPS stream
    except WebSocketDisconnect:
        pass
